from secrets import choice
from random import SystemRandom


def key(symbols='𒀀𒀁𒀂𒀃𒀄𒀅𒀆𒀇𒀈𒀉𒀊𒀋𒀌𒀍𒀎𒀏𒀐𒀑𒀒𒀓𒀔𒀕𒀖𒀗𒀘𒀙𒀚𒀛𒀜𒀝𒀞𒀟𒀠𒀡𒀢𒀣𒀤𒀥𒀦𒀧𒀨𒀩𒀪𒀫𒀬𒀭𒀮𒀯𒀰𒀱𒀲𒀳𒀴𒀵𒀶𒀷𒀸𒀹𒀺𒀻𒀼𒀽𒀾𒀿𒁀𒁁𒁂𒁃𒁄𒁅𒁆𒁇𒁈𒁉𒁊𒁋𒁌𒁍𒁎𒁏𒁐𒁑𒁒𒁓𒁔𒁕𒁖𒁗𒁘𒁙𒁚𒁛𒁜𒁝𒁞𒁟𒁠𒁡𒁢𒁣𒁤𒁥𒁦𒁧𒁨𒁩𒁪𒁫𒁬𒁭𒁮𒁯𒁰𒁱𒁲𒁳𒁴𒁵𒁶𒁷𒁸𒁹𒁺𒁻𒁼𒁽𒁾𒁿𒂀𒂁𒂂𒂃𒂄𒂅𒂆𒂇𒂈𒂉𒂊𒂋𒂌𒂍𒂎𒂏𒂐𒂑𒂒𒂓𒂔𒂕𒂖𒂗𒂘𒂙𒂚𒂛𒂜𒂝𒂞𒂟𒂠𒂡𒂢𒂣𒂤𒂥𒂦𒂧𒂨𒂩𒂪𒂫𒂬𒂭𒂮𒂯𒂰𒂱𒂲𒂳𒂴𒂵𒂶𒂷𒂸𒂹𒂺𒂻𒂼𒂽𒂾𒂿𒃀𒃁𒃂𒃃𒃄𒃅𒃆𒃇', start=2, stop=4):
    a = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    b = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    c = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    d = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    e = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    f = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    g = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    h = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    i = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    j = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    k = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    l = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    m = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    n = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    o = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    p = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    q = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    r = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    s = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    t = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    u = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    v = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    w = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    x = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    y = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    z = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    A = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    B = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    C = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    D = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    E = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    F = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    G = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    H = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    I = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    J = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    K = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    L = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    M = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    N = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    O = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    P = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    Q = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    R = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    S = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    T = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    U = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    V = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    W = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    X = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    Y = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    Z = ''.join(choice(symbols)
                for i in range(SystemRandom().randint(start, stop)))
    N1 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N2 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N3 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N4 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N5 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N6 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N7 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N8 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N9 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    N0 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S1 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S2 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S3 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S4 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S5 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S6 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S7 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S8 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S9 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    S10 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S11 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S12 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S13 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S14 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S15 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S16 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S17 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S18 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S19 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S20 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S21 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S22 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S23 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S24 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S25 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S26 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S27 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S28 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S29 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    S30 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R1 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R2 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R3 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R4 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R5 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R6 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R7 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R8 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R9 = ''.join(choice(symbols)
                 for i in range(SystemRandom().randint(start, stop)))
    R10 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R11 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R12 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R13 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R14 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R15 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R16 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R17 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R18 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R19 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    R20 = ''.join(choice(symbols)
                  for i in range(SystemRandom().randint(start, stop)))
    with open('key.py', 'w')as file:
        file.write("a='"+a+"';b='"+b+"';c='"+c+"';d='"+d+"';e='"+e+"';f='"+f+"';g='"+g+"';h='"+h+"';i='"+i+"';j='"+j+"';k='"+k+"';l='"+l+"';m='"+m+"';n='"+n+"';o='"+o+"';p='"+p+"';q='"+q+"';r='"+r+"';s='"+s+"';t='"+t+"';u='"+u+"';v='"+v+"';w='"+w+"';x='"+x+"';y='"+y+"';z='"+z+"';A='"+A+"';B='"+B+"';C='"+C+"';D='"+D+"';E='"+E+"';F='"+F+"';G='"+G+"';H='"+H+"';I='"+I+"';J='"+J+"';K='"+K+"';L='"+L+"';M='"+M+"';N='"+N+"';O='"+O+"';P='"+P+"';Q='"+Q+"';R='"+R+"';S='"+S+"';T='"+T+"';U='"+U+"';V='"+V+"';W='"+W+"';X='"+X+"';Y='"+Y+"';Z='"+Z+"';N1='"+N1+"';N2='"+N2+"';N3='"+N3+"';N4='"+N4+"';N5='"+N5+"';N6='"+N6+"';N7='"+N7+"';N8='"+N8 +
                   "';N9='"+N9+"';N0='"+N0+"';S1='"+S1+"';S2='"+S2+"';S3='"+S3+"';S4='"+S4+"';S5='"+S5+"';S6='"+S6+"';S7='"+S7+"';S8='"+S8+"';S9='"+S9+"';S10='"+S10+"';S11='"+S11+"';S12='"+S12+"';S13='"+S13+"';S14='"+S14+"';S15='"+S15+"';S16='"+S16+"';S17='"+S17+"';S18='"+S18+"';S19='"+S19+"';S20='"+S20+"';S21='"+S21+"';S22='"+S22+"';S23='"+S23+"';S24='"+S24+"';S25='"+S25+"';S26='"+S26+"';S27='"+S27+"';S28='"+S28+"';S29='"+S29+"';S30='"+S30+"';R1='"+R1+"';R2='"+R2+"';R3='"+R3+"';R4='"+R4+"';R5='"+R5+"';R6='"+R6+"';R7='"+R7+"';R8='"+R8+"';R9='"+R9+"';R10='"+R10+"';R11='"+R11+"';R12='"+R12+"';R13='"+R13+"';R14='"+R14+"';R15='"+R15+"';R16='"+R16+"';R17='"+R17+"';R18='"+R18+"';R19='"+R19+"';R20='"+R20+"'")


def encrypt():
